wanamudb:
  restart: always
  image: "api.wanamu.com:5043/wanamudb"
  ports:
    - 5432:5432
  environment:
    DB_NAME: wanamu
    POSTGRES_PASSWORD:
    POSTGRES_USER:
    DB_USER:
    DB_PASS:
    WANAMUDB_DATA:
    WANAMU_DB_DUMP:
  volumes:
    - $WANAMU_DB_DATA:/var/lib/postgresql/data
    - $WANAMU_DB_DUMP:/var/lib/postgresql/dumps
