wanamudb:
  restart: always
  build: .
  ports:
    5432:5432
  env_file:
    - ./wanamu-db.env
  volumes:
    - /var/lib/postgresql/data:/var/lib/postgresql/data
    - /var/lib/postgresql/dump:/var/lib/postgresql/dump