wanamudb:
  restart: always
  build: .
  ports:
    - 5432:5432
  environment:
    WU_DB_NAME: wanamu
    POSTGRES_PASSWORD:
    POSTGRES_USER:
    WU_DB_USER:
    WU_DB_PASS:
    WU_DB_DATA:
    WU_DB_DUMP:
  volumes:
    - /var/lib/postgresql/data:/var/lib/postgresql/data
    - ${$WU_DB_DUMP}:/var/lib/postgresql/dump
wanamudbmigration:
  build: ../wanamu-db-migration
  links:
    - wanamudb:db