wanamudb:
  restart: always
  build: .
  ports:
    - 5432:5432
  environment:
    DB_NAME: wanamu
    POSTGRES_PASSWORD:
    POSTGRES_USER:
    DB_USER:
    DB_PASS:
    WANAMU_DB_DATA:
    WANAMU_DB_DUMP:
  volumes:
    - /var/lib/postgresql/data:/var/lib/postgresql/data
    - /var/lib/postgresql/dump:/var/lib/postgresql/dump
wanamudbmigration:
  build: ../wanamu-db-migration
  links:
    - wanamudb:db